name: Mock deployment

on:
    workflow_dispatch:

permissions:
    deployments: write
    contents: write
    pull-requests: write

jobs:
    mock-deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Start Deployment
              uses: bobheadxi/deployments@v1
              id: deployment
              with:
                  step: start
                  token: ${{ secrets.SOME_TOKEN }}
                  ref: ${{ github.head_ref }}
                  env: Preview
                  override: false
                  debug: true

            - name: Update Deployment Status
              uses: bobheadxi/deployments@v1
              if: always()
              with:
                  step: finish
                  token: ${{ secrets.SOME_TOKEN }}
                  env: ${{ steps.deployment.outputs.env }}
                  override: false
                  status: ${{ job.status }}
                  deployment_id: ${{ steps.deployment.outputs.deployment_id }}
                  env_url: "https://google.com"
                  debug: true
