name: Test PR

on:
    pull_request:

permissions:
    deployments: write
    contents: write
    pull-requests: write

jobs:
    mock-deployment:
        runs-on: ubuntu-latest
        # echo " running with huntabytes code"
        steps:
            - name: Do something
              run: echo "running with huntabytes code"
