name: Test PR Target

on:
    pull_request_target:
        types:
            - opened
            - labeled
            - synchronize

permissions:
    deployments: write
    contents: write
    pull-requests: write

jobs:
    mock-deployment:
        runs-on: ubuntu-latest
        # echo " running with huntabytes code"
        steps:
            - name: Do something
              run: echo "running with huntabytes code"
